### ISSUE TITLE
Animation: last item removal is weird. :-)

### ISSUE THREAD

**Issue by studiotbt** [tomasko126/notemark#24]
Notes arent sliding down when last item is removed. it pops away.

**Comment by tomasko126** [comment]
@studiotbt I cannot reproduce this issue myself :(

**Comment by studiotbt** [comment]
![pop_lastitem](https://cloud.githubusercontent.com/assets/13738104/10118096/4031aefc-646f-11e5-8bce-363d957584e4.gif)
see gif, it pops down. instead of sliding. its a tiny but noticible :-)

**Comment by studiotbt** [comment]
ill look into it, i think i can fix it.
