### ISSUE TITLE
Multiple Browser Windows focus

### ISSUE THREAD

**Issue by studiotbt** [tomasko126/notemark#38]
1. add note.
2. open new browser window
3. add note - this will remove the added note even if its a different site.
4. add note again (this will add the same note from the first window.

**Comment by tomasko126** [comment]
@studiotbt Cannot reproduce this bug. Can you try to reproduce it again? Thanks!

**Comment by tomasko126** [comment]
I am closing this issue. If you are still able to reproduce it, please create a new issue. Thanks!
