### ISSUE TITLE
Unable to add note if page is not fully loaded

### ISSUE THREAD

**Issue by studiotbt** [tomasko126/notemark#5]
- If page is not completely loaded, I am unable to notemark it.
- is the extension able to get the favicon and the link first?

**Comment by tomasko126** [comment]
@studiotbt 
#1 Confirmed!
#2 What do you exactly mean?

**Comment by studiotbt** [comment]
#2 If the extension can grab the website favicon and the URL first, but if you can fix it either way it should be fine.

**Comment by tomasko126** [comment]
@studiotbt This has been fixed in https://github.com/tomasko126/notemark/pull/13
