### ISSUE TITLE
Security warning on Chrome

### ISSUE THREAD

**Issue by ghost** [tomasko126/notemark#70]
When I open the add-on, there's a security warning on Chrome.

**Comment by tomasko126** [comment]
@iampox I was not able to trigger a security warning when opening Notemark.
Could you please take a screenshot of the security warning and attach it here? Thanks!

**Comment by ghost** [comment]
My bad, it was because one of my bookmarked sites had a security warning, so when I opened Notemark, the security was triggered and showed up in the Notemark window.

**Comment by tomasko126** [comment]
@iampox Ah, alright, I am closing this issue then.
